version: "3"
services:
  app:
    build: .
    environment: 
      - CONTAINER_ID=f61e66b1ceca
      - RAM_LIMIT=0.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./vol:/opt/vol"